const DRILLS = [
  { cat: "Wrist & Shoulder Prep", color: "#2E6DA4", drills: [
    ["hs_001","Wrist circles","2 × 10 each direction, each orientation","Beginner","Forward + backward. Never skip — wrists are the most loaded joint in HS.",true,"mobility","none","low"],
    ["hs_002","Wrist flexion/extension stretch","2 × 30 sec","Beginner","On floor, fingers forward then backward. Full range each direction.",true,"mobility","none","low"],
    ["hs_003","Wrist extensor stretch","60 sec","Beginner","Backs of hands on floor, fingers pointing toward knees, sit back gently. Non-negotiable after every session.",true,"mobility","none","low"],
    ["hs_004","Finger extension stretch","30 sec each hand","Beginner","Pull fingers back toward wrist. Most people only stretch flexors — extensors need it too.",false,"mobility","none","low"],
    ["hs_005","Prayer stretch","2 × 30 sec","Beginner","Palms together, push down. Wrist flexor stretch.",false,"mobility","none","low"],
    ["hs_006","Reverse prayer stretch","2 × 30 sec","Beginner","Backs of hands together, push up. Wrist extensor stretch.",false,"mobility","none","low"],
    ["hs_007","Wrist weight shifts on all fours","2 × 10 reps","Beginner","Shift weight forward over knuckles then to fingertips. Wrist loading under movement.",true,"mobility","none","low"],
    ["hs_008","Quadruped weight shifts","3 × 10 reps","Beginner","On hands and knees, shift weight forward over wrists. First wrist loading drill — do before bear walks.",false,"mobility","none","low"],
    ["hs_009","Plank wrist rotations","3 × 10 reps","Beginner","In plank, rotate bodyweight in small circles over wrists. Wrist mobility under load.",false,"mobility","none","low"],
    ["hs_010","Wrist roller conditioning","3 × full roll","Intermediate","Roll weight up and down. Direct forearm endurance for sustained holds.",false,"strength","misc","low"],
    ["hs_011","Wrist flicks","30 reps","Beginner","Loose flicks after every session. Flushes blood through tendons and ligaments.",true,"mobility","none","low"],
    ["hs_012","Rice bucket training","3 × 2 min","Beginner","Plunge hand in rice, rotate and grab. Classical finger/wrist conditioning.",false,"strength","misc","low"],
    ["hs_013","Dead hang finger curls","3 × 10 reps","Beginner","Hang from bar, curl fingers open and closed. Tendon health maintenance.",false,"strength","bar","low"],
    ["hs_014","Wall shoulder opener","3 × 30 sec","Beginner","Arms overhead on wall, let chest drop toward floor. Opens thoracic and shoulder flexion.",true,"mobility","wall","low"],
    ["hs_015","Overhead shoulder shrugs","3 × 10 reps","Beginner","Arms overhead, elevate and depress scapula. Isolates the exact HS shoulder action.",true,"strength","none","low"],
    ["hs_016","Wall slides","3 × 10 reps","Beginner","Forearms on wall, slide up. Scapular upward rotation — critical for overhead stability.",true,"strength","wall","low"],
    ["hs_017","Pike push-ups","3 × 8 reps","Beginner","Shoulder pressing strength with bodyweight. Direct HS press preparation.",false,"strength","none","low"],
    ["hs_018","Cuban press","3 × 10 reps","Intermediate","External rotation strength — injury prevention for overhead training.",false,"strength","misc","low"],
    ["hs_019","Bottom-up KB press","3 × 5 each","Intermediate","KB upside down, extremely unstable. Forces wrist and shoulder stability simultaneously.",false,"strength","kb","medium"],
    ["hs_020","Bottom-up KB hold overhead","3 × 20 sec","Intermediate","Just hold the inverted KB overhead. Pure shoulder micro-stability endurance.",false,"strength","kb","medium"],
    ["hs_021","Banded overhead distraction","2 × 30 sec","Intermediate","Band around wrist overhead, let it pull. Opens shoulder capsule.",false,"mobility","band","low"],
    ["hs_022","Resistance band assisted HS hold","5 × 20 sec","Intermediate","Band anchored above pulls your hips up. Allows longer holds and better shape awareness.",false,"balance","band","low"],
    ["hs_023","Supinated grip HS on wall","3 × 20 sec","Advanced","Fingers pointing outward. Trains different wrist and forearm muscles.",false,"strength","wall","medium"],
    ["hs_024","PVC overhead dislocates","3 × 10 reps","Beginner","Wide grip PVC or band, pass overhead from front to back. True end-range shoulder flexion/extension loading. Non-negotiable if you have shoulder tightness.",true,"mobility","misc","low"],
    ["hs_025","Stall bar shoulder flexion stretch","3 × 30 sec","Intermediate","Face away from stall bar, grip overhead bar, let body hang forward. Deep end-range shoulder flexion loading. Can substitute with high bar or door frame.",false,"mobility","bar","medium"],
    ["hs_026","Weighted shoulder flexion stretch","3 × 30 sec","Intermediate","Lie on bench, hold light plate overhead and let arms drop back. Gravity-loaded shoulder flexion end range.",false,"mobility","misc","low"],
    ["hs_027","Prone shoulder lift-offs","3 × 10 reps","Intermediate","Lie face down, arms overhead, lift arms off floor and hold 2 sec. Posterior shoulder and lower trap strength — fixes dropping shoulders in HS.",false,"strength","none","low"],
    ["hs_028","Stop to fist down","2 × 10 each hand","Beginner","From stop (fingers up) to fist down.",true,"mobility","none","low"],
   
  ]},
  { cat: "Elbow Prep & Lockout", color: "#4A3060", drills: [
    ["hs_028","Straight-arm awareness drill","Every session","Beginner","Stand with arms overhead. Lock elbows fully. Feel the difference between soft and locked. This is what you need in every HS.",true,"technique","none","low"],
    ["hs_029","Elbow-pit forward cue drill","10 kick-ups","Beginner","In wall HS, consciously rotate elbow pits to face forward (toward the wall). Activates biceps as stabilizers and prevents hyperextension pain.",true,"technique","wall","low"],
    ["hs_030","Elbow lockout holds in plank","3 × 30 sec","Beginner","In straight-arm plank, squeeze elbows fully locked. Feel the active lockout — not passive hanging into the joint.",true,"strength","none","low"],
    ["hs_031","Supine elbow lockout press","3 × 10 reps","Beginner","Lie on back, arms vertical holding light weight. Lock elbows hard at top. Trains active lockout strength.",false,"strength","misc","low"],
    ["hs_032","Elbow hyperextension check","Each kick-up","Beginner","If elbows bend past straight (hyperextension), engage biceps slightly — micro-bend intention, not actual bend. Prevents joint damage under load.",true,"technique","none","low"],
    ["hs_033","Tiger bend negative (elbow prep)","5 reps","Advanced","From HS, lower slowly to forearm stand. Eccentrically loads the elbow in the exact HS range.",false,"strength","none","high"],
    ["hs_034","Active elbow lock in wall HS","3 × 30 sec","Beginner","In wall HS, focus entirely on squeezing elbows straight. Don't just hold — actively fire the triceps.",true,"technique","wall","low"],
  ]},
  { cat: "Line Shape Details", color: "#1E3A5F", drills: [
    ["hs_035","Glute squeeze in hollow body","3 × 30 sec","Beginner","In hollow body hold, squeeze glutes as hard as possible. Triggers posterior pelvic tilt automatically — the two are linked.",true,"technique","none","low"],
    ["hs_036","Inner thigh squeeze drill","3 × 30 sec","Beginner","In wall HS, place a block or ball between knees/ankles and squeeze. Stops legs separating and activates midline tension.",true,"technique","wall","low"],
    ["hs_037","Toes pointed drill","In every hold","Beginner","In wall HS, point toes hard. Not just aesthetic — activates full leg tension that locks the whole line from hip to toe.",true,"technique","wall","low"],
    ["hs_038","Posterior pelvic tilt isolation","3 × 10 reps","Beginner","Standing, tuck tailbone under and release. Feel the difference. Then carry this into your HS — it's what eliminates the banana.",true,"technique","none","low"],
    ["hs_039","Rib cage pulldown drill","3 × 30 sec","Beginner","In hollow body or wall HS, consciously pull the lower rib cage DOWN. This is a separate action from sucking in — you're closing the ribflare.",true,"technique","wall","low"],
    ["hs_040","Full body tension scan","Every hold","Beginner","From bottom up during wall HS: fingers pressing → elbows locked → shoulders active → ribs down → glutes squeezed → inner thighs together → toes pointed. Do this scan in every hold.",true,"technique","wall","low"],
    ["hs_041","Dead straight body hold on floor","3 × 20 sec","Beginner","Lie face up, squeeze everything simultaneously — glutes, thighs, abs, toes pointed, arms overhead. This is the exact tension needed for a good HS.",true,"technique","none","low"],
    ["hs_042","Tension jump drill","5 reps","Beginner","Stand relaxed, then on a signal fire every muscle simultaneously (glutes, abs, legs, arms overhead). Trains the quick full-body tension onset needed at kick-up.",false,"technique","none","low"],
  ]},
  { cat: "Foundation & Body Shape", color: "#1A2E45", drills: [
    ["hs_043","Hollow body floor hold","4 × 20–30 sec","Beginner","Lower back pressed flat, arms by ears, chin neutral. The core shape of every handstand.",true,"strength","none","low"],
    ["hs_044","Hollow body rocks","3 × 10 rocks","Beginner","Rock front to back WITHOUT losing hollow shape. Trains active core under movement.",true,"strength","none","low"],
    ["hs_045","Hollow body breathing","3 × 30 sec","Beginner","Hold hollow and breathe normally. Trains maintaining shape while breathing in HS.",true,"technique","none","low"],
    ["hs_046","Arch-to-hollow switch on floor","3 × 10 reps","Beginner","Controlled oscillation between arch and hollow. Builds body shape awareness.",false,"technique","none","low"],
    ["hs_047","Candlestick hold","4 × 20 sec","Beginner","Lie on back, legs straight up at 90°, lower back flat. Teaches vertical leg alignment without balance challenge.",false,"technique","none","low"],
    ["hs_048","Candlestick rocks","3 × 10 reps","Beginner","From candlestick, rock back onto shoulders and return. Spinal articulation and inversion confidence.",false,"technique","none","low"],
    ["hs_049","Dead bug","3 × 10 reps each","Beginner","Opposite arm and leg extend, lower back stays flat. Hollow body under load — direct HS core transfer.",false,"strength","none","low"],
    ["hs_050","Dead bug with reach","3 × 10 reps each","Intermediate","Both arms reach overhead at full extension. Mimics the exact arm position and core demand of a HS.",false,"strength","none","low"],
    ["hs_051","Straight-arm plank hold","4 × 30 sec","Beginner","Straight arms, shoulders elevated. Directly trains HS shoulder position.",true,"strength","none","low"],
    ["hs_052","Plank shoulder shrugs","3 × 10 reps","Beginner","In plank: protract and retract scapula. Isolates scapular control — essential for active HS.",true,"strength","none","low"],
    ["hs_053","Wall HS with physioball between legs","5 × 20 sec","Intermediate","Squeeze physioball between thighs. Activates adductors and midline tension — stops legs drifting apart.",false,"technique","wall","low"],
    ["hs_054","HS with dowel rod along spine","5 × 20 sec","Intermediate","Dowel rod along back (head, thoracic, tailbone). Instant alignment feedback — any arch shows immediately.",false,"technique","wall","misc"],
  ]},
  { cat: "Inversion Intro & Pike", color: "#0D4F6B", drills: [
    ["hs_055","Downward dog hold","3 × 30 sec","Beginner","Hands and feet on floor, hips high. Gets wrists, shoulders and hamstrings ready simultaneously.",true,"mobility","none","low"],
    ["hs_056","Dolphin pose hold","3 × 30 sec","Beginner","Forearms on floor, hips high. Shoulder endurance without full wrist load.",false,"strength","none","low"],
    ["hs_057","Dolphin push-ups","3 × 10 reps","Beginner","From dolphin pose, lower head toward floor and push back up. Direct shoulder strength.",false,"strength","none","low"],
    ["hs_058","Pike stand against wall","3 × 30 sec","Beginner","Feet high on wall, hands on floor, body in pike. First real inversion with full bodyweight on hands.",true,"strength","wall","low"],
    ["hs_059","Box handstand hold","5 × 30 sec","Beginner","Hands on floor, feet on box at hip height. First real wrist loading drill.",true,"strength","box","low"],
    ["hs_060","Box handstand shoulder shrugs","3 × 10 reps","Beginner","In box HS, shrug shoulders up and down. First serratus drill in an actual inversion.",false,"strength","box","low"],
    ["hs_061","Elevated pike hold — high box","5 × 30 sec","Intermediate","Feet on high box, hips above shoulders. As close to a HS as you can get without kicking up.",false,"strength","box","low"],
    ["hs_062","Pike on box — heel drive","3 × 10 reps","Beginner","In box pike, push heels toward ceiling one at a time. Teaches the kick-up motion under controlled load.",false,"technique","box","low"],
    ["hs_063","Wall handstand walk-in","10 reps","Beginner","Stand facing wall, walk hands down into HS position. Progressive wrist loading before any kick-up.",false,"technique","wall","low"],
    ["hs_064","Bear walk forward/backward","3 × 5m","Beginner","Hands and feet, knees hovering. Foundation for all hand walking drills.",false,"strength","none","low"],
    ["hs_065","Pike walks on hands","3 × 5m","Beginner","Hips high, legs straight, walk hands forward and backward. Wrist endurance under movement.",false,"strength","none","low"],
    ["hs_066","Pike hops","3 × 10 reps","Beginner","In pike, both hands hop forward together. First dynamic hand movement drill.",false,"technique","none","low"],
    ["hs_067","Frog stand hold","4 × 20 sec","Beginner","Squat, balance knees on triceps. First true bodyweight balance on hands.",false,"balance","none","low"],
  ]},
  { cat: "Wall Drills", color: "#1A3A2A", drills: [
    ["hs_068","Wall HS hold — chest to wall","5 × 45 sec","Beginner","Hips above shoulders, ribs in, no arch. Stack: wrists → elbows → shoulders → hips → heels.",true,"balance","wall","low"],
    ["hs_069","Wall HS hold — back to wall","5 × 45 sec","Beginner","Easier entry, good for beginners. Watch for arch tendency.",true,"balance","wall","low"],
    ["hs_070","Wall tuck HS hold","5 × 20 sec","Beginner","Back to wall, knees tucked. Finds balance point without full straight-body challenge.",true,"balance","wall","low"],
    ["hs_071","Wall straddle HS hold","5 × 20 sec","Beginner","Back to wall, legs wide. Lower CoM — easier to feel true vertical.",false,"balance","wall","low"],
    ["hs_072","Wall pike HS hold","5 × 20 sec","Intermediate","Back to wall, hips piked. Pike shape under safe conditions.",false,"technique","wall","low"],
    ["hs_073","Wall HS slide to tuck","5 reps","Beginner","From wall HS, bring knees to chest and back out. Manipulate shape without losing balance over hands.",true,"technique","wall","low"],
    ["hs_074","Wall HS slide to straddle","5 reps","Intermediate","Open legs to straddle and back. Centre of mass shift control.",false,"technique","wall","low"],
    ["hs_075","Wall HS slide to pike","5 reps","Intermediate","Pike hips forward to horizontal and back up. Eccentric and concentric press control.",false,"strength","wall","low"],
    ["hs_076","Wall HS kick-up consistency","15 reps","Beginner","Same leg every rep. Same height, same position. Muscle memory.",true,"technique","wall","low"],
    ["hs_077","Wall HS shoulder shrugs","3 × 10 reps","Beginner","In wall HS, push floor and release 10 times. Serratus endurance.",true,"strength","wall","low"],
    ["hs_078","Wall HS rib check","3 × 20 sec","Beginner","Pull ribs in then release. Feel the difference — ribs IN is correct.",false,"technique","wall","low"],
    ["hs_079","Fingertip pressure in wall HS","4 × 20 sec","Beginner","Shift weight to fingertips and back repeatedly. Trains balance reflex.",true,"balance","wall","low"],
    ["hs_080","Finger pressure hold test","3 × 10 sec","Beginner","Press fingertips so hard heels of hands lift slightly. Single most important drill for freestanding balance.",true,"balance","wall","low"],
    ["hs_081","Kick-up shape audit","10 reps","Beginner","Kick up, freeze, scan: wrists stacked? Elbows locked? Shoulders active? Ribs in? Hips over?",false,"technique","wall","low"],
    ["hs_082","Toes-only wall touch","5 × 30 sec","Intermediate","Back to wall, only toes contact. Goal: toes barely touching.",true,"balance","wall","low"],
    ["hs_083","One big toe touch","5 × 20 sec","Intermediate","Only one big toe on wall, other foot free.",true,"balance","wall","low"],
    ["hs_084","Alternating toe taps","3 × 10 reps","Intermediate","Tap one foot off and on the wall repeatedly. Single-leg stability.",false,"balance","wall","low"],
    ["hs_085","Heel drag down the wall","5 reps","Intermediate","Slowly lower heels down wall. Eccentric control.",false,"strength","wall","low"],
    ["hs_086","Walk hands away from wall","5 × 10 sec","Intermediate","Walk hands 5–10 cm away from wall. Harder balance point.",false,"balance","wall","low"],
    ["hs_087","Wall HS negatives","5 reps","Intermediate","Kick up, hold, slowly lower one leg at a time. Eccentric shoulder strength.",false,"strength","wall","low"],
    ["hs_088","Handstand push-ups on wall","3 × 5 reps","Advanced","Full ROM HS push-up against wall.",false,"strength","wall","medium"],
    ["hs_089","Deficit HS push-ups","3 × 5 reps","Advanced","Hands on parallettes or plates — deeper ROM.",false,"strength","parallettes","medium"],
    ["hs_090","Wall HS with head turn","3 × 20 sec","Intermediate","Slowly turn head left and right. Trains balance as vestibular input changes.",false,"balance","wall","low"],
    ["hs_091","Chest-to-wall shoulder touch","5 × 10 reps","Beginner","Lower one shoulder toward wall and back. Unilateral shoulder control.",false,"strength","wall","low"],
    ["hs_092","Wall HS hold with leg split","5 × 20 sec","Beginner","One leg on wall, one free. First asymmetric load.",false,"balance","wall","low"],
    ["hs_093","Wall HS — controlled one-leg lower","5 reps each","Intermediate","Lower one leg slowly to horizontal and hold 3 sec. Single-leg eccentric.",false,"strength","wall","low"],
  ]},
  { cat: "Balance & Fingertip Control", color: "#1A6B3A", drills: [
    ["hs_094","Fingertip rescue drill","10 reps","Intermediate","Intentionally tip forward then rescue with fingertips. Active balance reflex.",true,"balance","none","medium"],
    ["hs_095","Controlled over-balance drill","5 reps","Intermediate","Kick up, tip slightly forward, rescue. Trains balance recovery.",true,"balance","none","medium"],
    ["hs_096","Tipping point holds — forward and back","5 reps each","Intermediate","Find the very edge of balance in both directions intentionally.",false,"balance","none","medium"],
    ["hs_097","Underbalance correction drill","5 reps","Intermediate","Kick up, intentionally under-kick so hips fall short of vertical, then save by pushing harder through shoulders to drive hips up. Most people only practice over-balance recovery.",true,"balance","none","medium"],
    ["hs_098","Shoulder save drill","5 reps","Intermediate","In wall HS, deliberately let shoulders drop slightly toward floor, then re-elevate by pushing floor hard. Trains the shoulder press rescue that stops folds at the shoulder.",true,"technique","wall","low"],
    ["hs_099","Step-out save drill","10 reps","Intermediate","Kick up freestanding, when balance is lost sideways, take a controlled step with one hand to recover. The most practical save in real training.",true,"balance","none","medium"],
    ["hs_100","Finger spread awareness drill","In every hold","Beginner","Consciously spread all fingers maximally wide. More contact = more control.",true,"balance","none","low"],
    ["hs_101","Individual finger lifts on floor","3 × 10 each","Beginner","In plank, lift each finger one at a time. Finger-by-finger awareness.",false,"technique","none","low"],
    ["hs_102","Pinky engagement drill","3 × 20 sec","Intermediate","Actively press pinky into floor. Most people ignore it.",false,"balance","none","low"],
    ["hs_103","Wrist angle experiments","5 reps each","Intermediate","Try 0°, 15°, 30° hand turnout. Find YOUR optimal angle.",false,"technique","none","low"],
    ["hs_104","HS balance timer","End of session","All levels","Film, count seconds, log weekly. Non-negotiable progress tracking.",true,"balance","none","low"],
  ]},
  { cat: "Kick-Up Technique", color: "#C75B00", drills: [
    ["hs_105","Lunge entry practice","15 reps","Beginner","Just the lunge step — plant hands, shift weight, feel the moment before kick. Most beginners never isolate this.",true,"technique","none","low"],
    ["hs_106","Dominant leg kick-up practice","15 reps","Beginner","Same leg every rep, always.",true,"technique","none","low"],
    ["hs_107","Slow kick-up","10 reps","Intermediate","Kick as slowly as possible — removes momentum, forces shoulder and core strength.",true,"technique","none","low"],
    ["hs_108","Line drill kick-up","15 reps","Beginner","Tape a line, place index fingers ON it every rep.",false,"technique","none","low"],
    ["hs_109","Straddle kick-up","10 reps","Beginner","Legs wide going up — lower CoM, easier initial balance.",true,"technique","none","low"],
    ["hs_110","Kick-up → bail immediately","10 reps","Beginner","Kick up, immediately bail. Builds confidence, removes fear.",true,"technique","none","low"],
    ["hs_111","Cartwheel practice","10 reps each side","Beginner","The most important bail drill. Bad cartwheel = bad bail.",true,"technique","none","low"],
    ["hs_112","Cartwheel to HS freeze attempt","5 reps each side","Intermediate","Full cartwheel, pause at vertical. Most natural entry into freestanding HS.",false,"balance","none","medium"],
    ["hs_113","Back-to-wall kick-up","10 reps","Beginner","Kick into wall — for timid kickers who always under-kick.",false,"technique","wall","low"],
  ]},
  { cat: "Bailout Progression", color: "#8B4000", drills: [
    ["hs_114","Step-out bail","10 reps","Beginner","Simplest bail: when tipping, step one foot down and stand up. Learn this before anything else.",true,"technique","none","low"],
    ["hs_115","Quarter-turn bail","10 reps","Beginner","Step out but rotate 90° as you land so you face sideways. Safer landing in tight spaces.",true,"technique","none","low"],
    ["hs_116","Cartwheel bail","10 reps each side","Beginner","Full cartwheel exit. Arms stay straight throughout. Standard bail.",true,"technique","none","low"],
    ["hs_117","Forward roll bail","5 reps","Intermediate","Tuck chin, roll forward. Advanced exit — practice on soft mat first.",false,"technique","misc","medium"],
    ["hs_118","Bail choice drill","10 reps","Intermediate","Kick up, partner calls 'step', 'turn', or 'roll' just before you need to bail. Trains real-time bail selection.",false,"technique","partner","medium"],
  ]},
  { cat: "Freestanding Hold Development", color: "#5B2A8C", drills: [
    ["hs_119","Chest-to-wall freestanding attempt","10 kick-ups","Beginner","Kick up facing wall, stop before touching. Wall is there but don't use it.",true,"balance","wall","low"],
    ["hs_120","Kick-up into freestanding — arrive only","15–20 reps","Intermediate","Just reach vertical and bail. Focus on arriving, not holding.",true,"balance","none","medium"],
    ["hs_121","Kick-up + hold attempt + log","3 attempts","Intermediate","Every session: 3 max-effort holds. Record seconds. The fundamental daily metric.",true,"balance","none","medium"],
    ["hs_122","Accumulation holds","60 sec total/session","Intermediate","Goal: 60 sec total freestanding time per session across any lengths.",true,"balance","none","medium"],
    ["hs_123","Tuck HS hold","5 × 10–20 sec","Beginner","Fully tucked — most stable shape. Find balance point here first.",true,"balance","none","low"],
    ["hs_124","One-toe spot to freestanding","10 kick-ups","Intermediate","One big toe on wall. Remove it the moment you feel vertical.",true,"balance","wall","low"],
    ["hs_125","PR attempt protocol","3 max attempts","All levels","Always attempt max hold FIRST, before any fatigue.",true,"balance","none","medium"],
    ["hs_126","Greasing the groove","Every 1–2 hours","All levels","3–5 kick-ups throughout the day. Best neural encoding method.",true,"technique","none","low"],
    ["hs_127","EMOM kick-ups","10 min EMOM","Intermediate","Every minute: 3 kick-ups. Volume + consistency.",false,"conditioning","none","medium"],
    ["hs_128","Ladder set holds","1–2–3–4–5 sec","Intermediate","Hold 1 sec, rest. Hold 2 sec, rest. Climb the ladder.",false,"balance","none","medium"],
  ]},
  { cat: "Press Handstand Prep", color: "#6B1A1A", drills: [
    ["hs_129","Toe pulls","3 × 10 reps","Intermediate","Seated straddle, reach to toes and pull yourself deeper. Active hip flexion loading — direct compression strength.",true,"strength","none","low"],
    ["hs_130","Seated pancake leg lifts","3 × 10 reps","Intermediate","In straddle, lift both legs off floor and hold 3 sec. Compression strength with wide legs.",true,"strength","none","low"],
    ["hs_131","Elephant press","5 reps","Intermediate","Standing straddle, fold down, place hands on floor, pike-press hips up. Teaches the weight shift needed for press HS entry.",true,"strength","none","medium"],
    ["hs_132","Press walks","3 × 5m","Intermediate","In straddle fold, walk hands forward slowly while keeping legs straight. Progressive shoulder loading in press position.",true,"strength","none","low"],
    ["hs_133","Standing compression raises","3 × 10 reps","Intermediate","Standing, lift one straight leg forward as high as possible. Active hip flexion range — trains the compression needed to lift legs in press HS.",true,"strength","none","low"],
    ["hs_134","L-sit hold","4 × 10–20 sec","Intermediate","On parallettes or floor. Compression strength foundation.",true,"strength","parallettes","low"],
    ["hs_135","Straddle compression hold","4 × 20 sec","Intermediate","Seated straddle, lift legs off floor. Compression strength with wide legs.",true,"strength","none","low"],
    ["hs_136","Tuck compression hold","4 × 20 sec","Beginner","Seated, pull knees to chest without hands. Hip flexor compression.",false,"strength","none","low"],
    ["hs_137","Straddle press negatives","5 reps","Intermediate","Stand in straddle, slowly lower hands to floor. Eccentric press HS.",false,"strength","none","medium"],
    ["hs_138","Tuck press negatives","5 reps","Beginner","Tucked version of press negative. Easier entry to press prep.",false,"strength","none","low"],
    ["hs_139","Box pike press","5 reps","Intermediate","Feet on box, press toward vertical.",false,"strength","box","medium"],
    ["hs_140","Parallette L-sit to tuck","5 reps","Intermediate","From L-sit on parallettes, pull knees to chest.",false,"strength","parallettes","low"],
    ["hs_141","Parallette tuck to HS attempt","3 reps","Advanced","From tuck on parallettes, press to full HS.",false,"strength","parallettes","high"],
    ["hs_142","Press HS from L-sit on bars","3 × 3 reps","Elite","From L-sit, press up to HS. Elite pressing strength.",false,"strength","bar","high"],
  ]},
  { cat: "Strength Builders", color: "#8B1A1A", drills: [
    ["hs_143","Pike compression holds","4 × 20 sec","Intermediate","Seated, compress legs to chest. Trains hip flexion for press HS.",false,"strength","none","low"],
    ["hs_144","Serratus push-ups","3 × 10 reps","Beginner","At top of push-up, push extra into floor. Scapular protraction.",true,"strength","none","low"],
    ["hs_145","Scapular wall slides","3 × 10 reps","Beginner","Forearms on wall, slide arms up. Serratus activation.",true,"strength","wall","low"],
    ["hs_146","Handstand shrugs on wall","3 × 10 reps","Beginner","In wall HS, depress and elevate scapula.",false,"strength","wall","low"],
    ["hs_147","Z-press","3 × 8 reps","Intermediate","Seated on floor, overhead press. Mimics HS press demands.",false,"strength","misc","low"],
    ["hs_148","Loaded overhead carry","3 × 20m","Intermediate","KB overhead, walk 20m. Overhead stability endurance.",false,"conditioning","kb","low"],
    ["hs_149","Ring support hold RTO","4 × 20 sec","Intermediate","Straight-arm rings, rings turned out. Serratus and rotator cuff.",false,"strength","rings","medium"],
    ["hs_150","Band pull-aparts","3 × 15 reps","Beginner","Rear delt and rhomboid health. Antagonist balance for pressing.",false,"strength","band","low"],
    ["hs_151","Face pulls","3 × 15 reps","Beginner","Cable or band. External rotation — injury prevention.",false,"strength","band","low"],
    ["hs_152","Ring rows","3 × 10 reps","Beginner","Antagonist pulling work. Balances all the pushing.",false,"strength","rings","low"],
    ["hs_153","Ab wheel rollout","3 × 8 reps","Intermediate","Hollow body under load. Direct HS core transfer.",false,"strength","misc","medium"],
    ["hs_154","Hanging leg raises","3 × 10 reps","Intermediate","Compression + hollow body combined.",false,"strength","bar","low"],
    ["hs_155","Prone Y-T-W-L raises","3 × 10 reps","Beginner","Face down, raise arms in each letter shape. Full rotator cuff conditioning.",false,"strength","none","low"],
    ["hs_156","Scapular pull-ups","3 × 10 reps","Beginner","Hang, depress scapula only. Scapular control.",false,"strength","bar","low"],
  ]},
  { cat: "Flexibility & Mobility", color: "#4A7C59", drills: [
    ["hs_157","Overhead flexibility test","Daily","Beginner","Arms fully vertical by ears with hollow body while standing? If not, do daily.",true,"mobility","none","low"],
    ["hs_158","Hip flexor stretch","3 × 45 sec each","Beginner","Tight hip flexors cause arch in HS. Critical.",true,"mobility","none","low"],
    ["hs_159","Posterior pelvic tilt stretch","3 × 30 sec","Beginner","Lie on back, pull knees to chest, let lower back round into floor. Releases hip flexors and lower back — directly reduces HS arch.",true,"mobility","none","low"],
    ["hs_160","Pancake / straddle stretch","3 × 60 sec","Intermediate","Wide leg seated, chest to floor. For straddle HS and press HS.",false,"mobility","none","low"],
    ["hs_161","Pancake stretch rocking","3 × 10 reps","Intermediate","In straddle, rock forward and hold.",false,"mobility","none","low"],
    ["hs_162","90/90 hip stretch","3 × 45 sec each","Beginner","Sit in 90/90, lean forward over front shin. Hip flexor and external rotator.",false,"mobility","none","low"],
    ["hs_163","Thoracic extension on foam roller","3 × 30 sec","Beginner","Mid-back mobility. Tight thoracic causes arch in HS.",false,"mobility","foam_roller","low"],
    ["hs_164","Thoracic rotation drill","3 × 10 reps each","Beginner","Rotate thoracic spine through full range. Stiffness limits overhead range.",false,"mobility","none","low"],
    ["hs_165","Wall overhead reach","3 × 30 sec","Beginner","Stand facing wall, slide arms up while keeping hollow.",false,"mobility","wall","low"],
    ["hs_166","Lat stretch on bar","3 × 30 sec","Beginner","Hang, let lats lengthen. Opens overhead range.",false,"mobility","bar","low"],
    ["hs_167","Hamstring stretching","3 × 45 sec each","Beginner","Tight hamstrings affect kick-up and pike quality.",false,"mobility","none","low"],
  ]},
  { cat: "Gaze & Vestibular Training", color: "#2E6DA4", drills: [
    ["hs_168","Fixed gaze drill","Every kick-up","Beginner","Mark an X between hands before every kick-up. Look at it. Non-negotiable.",true,"technique","none","low"],
    ["hs_169","Eyes-closed wall HS","3 × 10 sec","Intermediate","Close eyes in wall hold. Vestibular system forced to activate.",false,"balance","wall","low"],
    ["hs_170","Head position experiments","5 reps each","Intermediate","Try neutral, tucked, extended. Find YOUR optimal.",false,"technique","none","low"],
    ["hs_171","Verbal counting in HS","Every hold","Beginner","Count out loud. Prevents breath-holding and trains dual-tasking.",false,"technique","none","low"],
    ["hs_172","Single leg balance eyes closed","3 × 30 sec each","Beginner","Stand on one leg, eyes closed. Basic vestibular baseline.",false,"balance","none","low"],
  ]},
  { cat: "Mental & Focus", color: "#0D6B5E", drills: [
    ["hs_173","Pre-kick-up ritual","Every session","All levels","Same 3 steps every time: set hands → look at spot → single breath → kick.",true,"mental","none","low"],
    ["hs_174","Visualization hold","3 × 30 sec","All levels","Close eyes, visualize perfect hold, THEN kick up.",false,"mental","none","low"],
    ["hs_175","Progressive relaxation in HS","3 × 30 sec","Intermediate","In wall hold, relax face, jaw, neck one at a time.",false,"mental","wall","low"],
    ["hs_176","Cue word anchor","Every hold","All levels","Pick one word (e.g. 'long') and repeat during every hold.",false,"mental","none","low"],
    ["hs_177","Video review at 0.5×","Weekly","All levels","Film every session from the side, watch at half speed.",true,"technique","none","low"],
    ["hs_178","Fear mapping","Once per week","Beginner","Write down what you're afraid of. Then practice that bail specifically.",false,"mental","none","low"],
    ["hs_179","Progressive hold log","Daily","All levels","Write best hold every single day. Most motivating data.",true,"technique","none","low"],
    ["hs_180","Breathing protocol holds","3 × max hold","Intermediate","Inhale before kick-up, exhale slowly during hold. Never hold breath beyond 3 sec.",true,"technique","none","low"],
  ]},
  { cat: "One-Arm HS Progression", color: "#7B3F00", drills: [
    ["hs_181","Wall weight shift — side to side","5 × 30 sec","Intermediate","In wall HS (chest to wall), shift ALL weight onto one arm slowly, then back. Other hand barely touches. This is the starting point for OAH.",true,"balance","wall","medium"],
    ["hs_182","Wall weight shift — fingertip assist","5 × 20 sec each","Intermediate","In wall HS, take one hand off and replace with just fingertips of same hand. Then 3 fingers, then 1.",true,"balance","wall","medium"],
    ["hs_183","Shoulder stack drill","3 × 20 sec","Intermediate","In wall HS, check: is the working shoulder directly above the wrist? Use a partner or video. OAH shoulder must be stacked perfectly.",true,"technique","wall","low"],
    ["hs_184","One-arm HS lean on wall","5 reps each","Advanced","Full body weight on one arm, other arm tucks behind back. Chest to wall for safety.",true,"balance","wall","high"],
    ["hs_185","Fingertip assist OAH","5 × 10 sec each","Advanced","In freestanding HS, take one hand off and replace with 2–3 fingertips of same hand. Build to 1 finger, then none.",false,"balance","none","high"],
    ["hs_186","Block squeeze OAH drill","5 × 10 sec each","Advanced","Place a yoga block under the non-working hand fingers. Focus on keeping pressure off block. Forces weight fully onto working arm.",false,"balance","misc","high"],
    ["hs_187","Straddle OAH line work","10 kick-ups","Advanced","In straddle HS, shift weight to one arm. Straddle lowers CoM and makes first OAH attempts more achievable.",false,"balance","none","high"],
    ["hs_188","OAH pirouette prep","3 reps each way","Elite","From two-arm HS, transfer weight to one arm and rotate 180°, land on other arm. Pirouette via brief OAH.",false,"balance","none","high"],
  ]},
  { cat: "Inversion Entry Variations", color: "#0D6B5E", drills: [
    ["hs_189","Headstand hold — tripod","4 × 30 sec","Beginner","Safe inversion practice. Inversion comfort.",false,"balance","none","low"],
    ["hs_190","Forearm stand hold","4 × 20 sec","Intermediate","Easier than HS. Inversion comfort with less wrist load.",false,"balance","none","low"],
    ["hs_191","Crow pose hold","4 × 20 sec","Beginner","Wrist loading comfort and inversion confidence.",false,"balance","none","low"],
  ]},
  { cat: "Advanced Variations", color: "#7B3F00", drills: [
    ["hs_192","HS pirouette","5 each way","Advanced","360° rotation. Weight shifts to one arm briefly.",false,"balance","none","high"],
    ["hs_193","HS walking forward","3 × 5m","Advanced","Walk on hands forward.",false,"conditioning","none","high"],
    ["hs_194","HS walking backward","3 × 5m","Advanced","Harder than forward — different weight shift.",false,"conditioning","none","high"],
    ["hs_195","HS push-up freestanding","3 × 3 reps","Advanced","Full range HS push-up without wall. Requires solid 10+ sec hold.",false,"strength","none","high"],
    ["hs_196","HS on parallettes","10 kick-ups","Intermediate","Wrist neutral, more finger range. Standard upgrade from floor.",false,"balance","parallettes","medium"],
  ]},
  { cat: "Proprioception & Instability", color: "#C75B00", drills: [
    ["hs_197","HS on balance board","5 attempts","Advanced","Rocks front-to-back — directly trains the most common imbalance axis.",false,"balance","misc","high"],
    ["hs_198","HS on folded yoga mat","5 kick-ups","Intermediate","Soft, slightly unstable — gentle intro to instability.",false,"balance","misc","medium"],
    ["hs_199","HS on parallettes turned out","5 kick-ups","Intermediate","External rotation at wrist. Different muscle engagement.",false,"balance","parallettes","medium"],
    ["hs_200","Towel grip HS","5 kick-ups","Advanced","Thin towel under palms. Forces finger micro-adjustments.",false,"balance","misc","high"],
  ]},
  { cat: "Transition Drills", color: "#5B2A8C", drills: [
    ["hs_201","HS → lower to pike","5 reps","Intermediate","Controlled descent to seated pike. Eccentric shoulder and core.",false,"strength","none","medium"],
    ["hs_202","HS → lower to straddle","5 reps","Intermediate","Controlled descent legs wide. Flexibility + eccentric strength.",false,"strength","none","medium"],
    ["hs_203","HS → walk → stop","3 × 3 steps","Advanced","Walk a few steps, try to stop and hold.",false,"balance","none","high"],
    ["hs_204","Cartwheel to HS stop","5 reps each way","Intermediate","Pause at vertical point during cartwheel.",false,"balance","none","medium"],
    ["hs_205","HS → bridge","3 reps","Advanced","Over-balance into backbend. Requires spinal flexibility.",false,"technique","none","high"],
  ]},
  { cat: "Partner Drills", color: "#8B1A1A", drills: [
    ["hs_206","Hip-hold spot","10 kick-ups","Intermediate","Partner holds hips — allows real micro-balance with safety.",false,"balance","partner","low"],
    ["hs_207","Ankle-hold spot","10 kick-ups","Beginner","Classic beginner spot. Removes fear completely.",false,"balance","partner","low"],
    ["hs_208","Partner alignment check","3 × 30 sec","Beginner","Partner stands side-on and calls cues while you hold.",false,"technique","partner","low"],
    ["hs_209","Partner verbal counting","Every hold","Beginner","Partner counts out loud. Frees all mental bandwidth.",false,"technique","partner","low"],
  ]},
  { cat: "Cooldown", color: "#2C4A6B", drills: [
    ["hs_210","Child's pose with arm reach","60 sec","Beginner","Kneel, sit back, arms forward. Decompress wrists, shoulders and spine.",true,"mobility","none","low"],
    ["hs_211","Passive hang","3 × 30 sec","Beginner","Dead hang from bar. Decompresses shoulder girdle and spine.",false,"mobility","bar","low"],
    ["hs_212","Supine shoulder stretch","60 sec each","Beginner","One arm across chest, pull gently. Posterior shoulder cooldown.",false,"mobility","none","low"],
    ["hs_213","Supine twist","60 sec each side","Beginner","Knee across body. Spinal rotation release.",false,"mobility","none","low"],
    ["hs_214","Seated forward fold","60 sec","Beginner","Legs straight, fold forward. Hamstrings and lower back.",false,"mobility","none","low"],
  ]},
];

const LEVEL_BADGE_STYLE = {
  "Beginner":     "background:#D4EDDA;color:#1A6B3A",
  "Intermediate": "background:#FFF3CD;color:#856404",
  "Advanced":     "background:#FDECEA;color:#8B1A1A",
  "Elite":        "background:#EDE0F7;color:#5B2A8C",
  "All levels":   "background:#E8F4FD;color:#2E6DA4",
};

const LEVEL_BADGE = {
  "Beginner":     "level-beginner",
  "Intermediate": "level-intermediate",
  "Advanced":     "level-advanced",
  "Elite":        "level-elite",
  "All levels":   "level-all",
};
